[package]
name = "crypto-bigint"
version = "0.7.0"
edition = "2024"

[dependencies]
real_crypto_bigint = { package = "crypto-bigint", version = "0.7", default-features = false, features = ["zeroize"] }

[features]
default = []
alloc = ["real_crypto_bigint/alloc"]
shalloc  = ["alloc"]
zeroize = ["real_crypto_bigint/zeroize"]
serde = ["real_crypto_bigint/serde"]
getrandom = ["real_crypto_bigint/getrandom", "rand_core"]
rand_core = ["real_crypto_bigint/rand_core"]
