[package]
name = "pkcs8"
version = "0.11.0-rc.10"
edition = "2024"

[dependencies]
real_pkcs8 = { package = "pkcs8", version = "0.11.0-rc.10", default-features = false, features = [] }
const-oid = { version = "0.10", default-features = false }
spki = { path = "../fake_spki", package = "spki", default-features = false, features = [] }

[features]
default = []
alloc = ["real_pkcs8/alloc", "spki/alloc"]
pem = ["real_pkcs8/pem"]
encryption = ["real_pkcs8/encryption"]
std = ["alloc", "real_pkcs8/std", "spki/std"]
